apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  # Change name to api-cluster-1
  name: api-test-cluster
  region: us-east-1
  version: "1.21"

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t3.small
  ssh:
    enableSsm: true

# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]