apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-pred-deployment
  labels:
    app: house-prediction-api
  namespace: house-prediction-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: house-prediction-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: house-prediction-api
    spec:
      containers:
      - image: theanalyst6/house-prediction-ml:latest
        imagePullPolicy: Always
        name: house-prediction-api
        ports:
        - containerPort: 80
          protocol: TCP