apiVersion: v1
kind: Service
metadata:
  name: house-pred-api-service
  namespace: house-prediction-namespace
spec:
  selector:
    app: house-prediction-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80