apiVersion: v1
kind: Service
metadata:
  name: house-pred-api-service-v${LABEL_VERSION}
  namespace: house-prediction-namespace
spec:
  type: LoadBalancer
  selector:
    app: house-prediction-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80