version: 2.1

commands:
    rollback_on_fail:
        parameters:
          label_version:
            type: string
        steps:
          - run:
              name: Rollback kubernetes deployment/service on failure
              command: |
                echo "Rolling back deployment and service"
                echo "${LABEL_VERSION}"
                export GREEN="-green"

                RESULT=$(kubectl get deployments -n ${KUBE_NAMESPACE} | grep "house-pred-deployment-${LABEL_VERSION}")
                if [ "${RESULT}" = "0" ];
                then
                    envsubst < ml-deployment.yml | kubectl delete -f -
                else
                    echo "Deployment not found"
                fi

                RESULT=$(kubectl get services -n ${KUBE_NAMESPACE} | grep "house-pred-api-service-green")
                if [ "${RESULT}" = "0" ];
                then
                    envsubst < ml-service.yml | kubectl delete -f -
                else
                    echo "Service not found"
                fi
                exit 0
              when: on_fail

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3

jobs:
    lint:
      docker:
          - image: python:3.7.3-stretch
      working_directory: ~/repo
      steps:
        - checkout
        - restore_cache:
            keys:
                - v1-dependencies-{{ checksum "requirements.txt" }}
                - v1-dependencies-
        - run:
            name: install dependencies
            command: |
                python3 -m venv venv
                . venv/bin/activate
                make install
                # Install hadolint
                wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
        - save_cache:
            paths:
                - ./venv
            key: v1-dependencies-{{ checksum "requirements.txt" }}
        - run:
            name: run lint
            command: |
                . venv/bin/activate
                make lint 

    test:
      docker:
            - image: python:3.7.3-stretch
      working_directory: ~/repo
      steps:
        - checkout
        - restore_cache:
            keys:
                - v1-dependencies-{{ checksum "requirements.txt" }}
                - v1-dependencies-
        - run:
            name: Start Flask application and run test
            command: |
                python3 -m venv venv
                . venv/bin/activate
                make install
                python3 app.py &
                sleep 5 # Wait for server to start
                ./make_prediction.sh 80
                RC=$(echo $?)
                if [ "${RC}" != "0" ];
                then
                    exit 1
                fi
        - save_cache:
            paths:
                - ./venv
            key: v1-dependencies-{{ checksum "requirements.txt" }}
                  
    build:
      docker:
            - image: circleci/buildpack-deps:stretch
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Install Basic Calculator
            command: |
              sudo apt install -y bc
        - run:
            name: Get latest label version
            command: |
              echo "${DOCKERHUB_PASS}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
              RESULT=$(./get_latest_tag.sh)
              LEN=${#RESULT}
              CURRENT_LABEL=${RESULT:1:${LEN}}
              LABEL_VERSION=$(echo ${CURRENT_LABEL} + 0.01 | bc -l)
              echo ${LABEL_VERSION/./-} > label_version.txt
              echo "export LABEL_VERSION=${LABEL_VERSION}" >> $BASH_ENV
        - run:
            name: Build Docker image with latest tag
            command: |
              docker build -t ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:v${LABEL_VERSION} .
              docker build -t ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest .
        - run:
            name: Archive Docker image
            command: |
              docker save -o image.tar ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:v${LABEL_VERSION}
              docker save -o image_latest.tar ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest
        - persist_to_workspace:
            root: .
            paths:
              - ./image.tar
              - ./image_latest.tar
              - ./label_version.txt
  
    push:
      docker:
            - image: circleci/buildpack-deps:stretch
      steps:
        - attach_workspace:
            at: /tmp/workspace
        - setup_remote_docker
        - run:
            name: Load archived Docker image
            command: |
              docker load -i /tmp/workspace/image.tar
              docker load -i /tmp/workspace/image_latest.tar
        - run: 
            name: Push to dockerhub
            command: |
              LABEL_VERSION=$(cat /tmp/workspace/label_version.txt)
              echo "export LABEL_VERSION=${LABEL_VERSION}" >> $BASH_ENV
              echo "${DOCKERHUB_PASS}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
              docker push ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest
              docker push ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:v${LABEL_VERSION/-/.}

    create_deployment:
        docker:
          - image: cimg/python:3.10.6
        steps:
          - attach_workspace:
                at: /tmp/workspace
          - run:
              name: Export label version
              command: |
                LABEL_VERSION=$(cat /tmp/workspace/label_version.txt)
                echo "export LABEL_VERSION=${LABEL_VERSION}" >> $BASH_ENV
          - checkout
          - run:
              name: Set up .aws directory
              command: |
                mkdir ~/.aws
                echo -e "[UdacityAdmin]\naws_access_key_id=${AWS_ACCESS_KEY_ID}\naws_secret_access_key=${AWS_SECRET_ACCESS_KEY}\n" > ~/.aws/credentials
          - aws-eks/update-kubeconfig-with-authenticator:
                  cluster-name: ${CLUSTER_NAME}
                  install-kubectl: true
                  aws-region: ${AWS_DEFAULT_REGION}
                  aws-profile: UdacityAdmin
          - kubernetes/create-or-update-resource:
                  action-type: apply
                  envsubst: true
                  get-rollout-status: true
                  namespace: ${KUBE_NAMESPACE}
                  resource-file-path: ml-deployment.yml
                  resource-name: deployment/house-pred-deployment-${LABEL_VERSION}
          - rollback_on_fail:
                  label_version: ${LABEL_VERSION}

    create_service:
        docker:
          - image: cimg/python:3.10.6
        steps:
          - attach_workspace:
                at: /tmp/workspace
          - run:
              name: Export label version
              command: |
                LABEL_VERSION=$(cat /tmp/workspace/label_version.txt)
                echo "export LABEL_VERSION=${LABEL_VERSION}" >> $BASH_ENV
                echo "export GREEN=-green" >> $BASH_ENV
          - checkout
          - run:
              name: Set up .aws directory
              command: |
                mkdir ~/.aws
                echo -e "[UdacityAdmin]\naws_access_key_id=${AWS_ACCESS_KEY_ID}\naws_secret_access_key=${AWS_SECRET_ACCESS_KEY}\n" > ~/.aws/credentials
          - aws-eks/update-kubeconfig-with-authenticator:
                  cluster-name: ${CLUSTER_NAME}
                  install-kubectl: true
                  aws-region: ${AWS_DEFAULT_REGION}
                  aws-profile: UdacityAdmin
          - kubernetes/create-or-update-resource:
                  action-type: apply
                  envsubst: true
                  get-rollout-status: false
                  namespace: ${KUBE_NAMESPACE}
                  resource-file-path: ml-service.yml
                  resource-name: service/house-pred-api-service${GREEN}
          - run:
              name: Get hostname of New Load Balancer
              command: |
                sleep(10) # Wait for service to come online
                #PREV_VERSION=$(echo ${LABEL_VERSION/-/.} - 0.01 | bc -l)
                kubectl get services -n ${KUBE_NAMESPACE} | grep "${LABEL_VERSION}" | awk '{ print $4}' > dns_host_name.txt
          - persist_to_workspace:
                root: .
                paths:
                  - ./dns_host_name.txt
          - rollback_on_fail:
                  label_version: ${LABEL_VERSION}

    smoke_test:
        docker:
          - image: cimg/python:3.10.6
        steps:
          - attach_workspace:
                at: /tmp/workspace
          - run:
              name: Run smoke test against Service Endpoint
              command: |
                DNS_SERVICE_NAME=$(cat /tmp/workspace/dns_host_name.txt)
                ./make_prediction.sh 80 ${DNS_SERVICE_NAME}
                RC=$(echo $?)
                if [ "${RC}" != "0" ];
                then
                    exit 1
                fi
          - rollback_on_fail:
                  label_version: ${LABEL_VERSION}

    repoint:
        docker:
          - image: cimg/python:3.10.6
        steps:
          - attach_workspace:
                at: /tmp/workspace
          - run:
                name: Export label version
                command: |
                  LABEL_VERSION=$(cat /tmp/workspace/label_version.txt)
                  echo "export LABEL_VERSION=${LABEL_VERSION}" >> $BASH_ENV
                  echo "export GREEN="" >> $BASH_ENV
          - run:
              name: Set up .aws directory
              command: |
                  mkdir ~/.aws
                  echo -e "[UdacityAdmin]\naws_access_key_id=${AWS_ACCESS_KEY_ID}\naws_secret_access_key=${AWS_SECRET_ACCESS_KEY}\n" > ~/.aws/credentials
          - aws-eks/update-kubeconfig-with-authenticator:
                  cluster-name: ${CLUSTER_NAME}
                  install-kubectl: true
                  aws-region: ${AWS_DEFAULT_REGION}
                  aws-profile: UdacityAdmin
          - kubernetes/create-or-update-resource:
                  action-type: apply
                  envsubst: true
                  get-rollout-status: false
                  namespace: ${KUBE_NAMESPACE}
                  resource-file-path: ml-service.yml
                  resource-name: service/house-pred-api-service

workflows:
      version: 2
      main_workflow:
            jobs:
              - lint
              - test
              - build:
                 requires:
                   - lint
                   - test
              - push:
                 requires:
                   - build
                 filters:
                   branches:
                     only: master
              - create_deployment:
                   requires:
                     - push
              - create_service:
                   requires:
                     - create_deployment
              # - smoke_test:
              #       requires:
              #         - create_service
              # - repoint:
              #      requires:
              #         - smoke_test
              # - delete_prev_version:
              #       requires:
              #         - repoint

