version: 2.1

jobs:
    lint:
      docker:
          - image: python:3.7.3-stretch
      working_directory: ~/repo
      steps:
        - checkout
        - restore_cache:
            keys:
                - v1-dependencies-{{ checksum "requirements.txt" }}
                - v1-dependencies-
        - run:
            name: install dependencies
            command: |
                python3 -m venv venv
                . venv/bin/activate
                make install
                # Install hadolint
                wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
        - save_cache:
            paths:
                - ./venv
            key: v1-dependencies-{{ checksum "requirements.txt" }}
        - run:
            name: run lint
            command: |
                . venv/bin/activate
                make lint 

    test:
      docker:
            - image: python:3.7.3-stretch
      working_directory: ~/repo
      steps:
        - checkout
        - restore_cache:
            keys:
                - v1-dependencies-{{ checksum "requirements.txt" }}
                - v1-dependencies-
        - run:
            name: Start Flask application and run test
            command: |
                python3 -m venv venv
                . venv/bin/activate
                make install
                python3 app.py &
                sleep 5 # Wait for server to start
                ./make_prediction.sh 80
                RC=$(echo $?)
                if [ "${RC}" != "0" ];
                then
                    exit 1
                fi
        - save_cache:
            paths:
                - ./venv
            key: v1-dependencies-{{ checksum "requirements.txt" }}
                  

    build:
      docker:
            - image: circleci/buildpack-deps:stretch
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build Docker image with latest tag
            command: |
              docker build -t ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest .
        - run:
            name: Archive Docker image
            command: docker save -o image.tar ${DOCKERHUB_USERNAME}/${IMAGE_NAME}
        - persist_to_workspace:
            root: .
            paths:
              - ./image.tar
  
    push:
      docker:
            - image: circleci/buildpack-deps:stretch
      steps:
        - attach_workspace:
            at: /tmp/workspace
        - setup_remote_docker
        - run:
            name: Load archived Docker image
            command: docker load -i /tmp/workspace/image.tar
        - run: 
            name: Push to dockerhub
            command: |
              echo "${DOCKERHUB_PASS}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
              docker push ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest


workflows:
      version: 2
      main_workflow:
            jobs:
              - lint 
              - test
              - build:
                  requires:
                    - lint
                    - test
              - push:
                  requires:
                    - build
                  filters:
                    branches:
                      only: master
