apiVersion: v1
kind: Service
metadata:
  name: house-pred-api-service${GREEN}
  namespace: house-prediction-namespace
spec:
  type: LoadBalancer
  selector:
    app: house-prediction-api
    version: ${LABEL_VERSION}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80